apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: simple-app
spec:
  template:
    spec:
      containers:
      - name: simple-app
        args:
        - --debug
        image: example.com/simple-app:a92bbcbf624c
