site_name: KTL
site_url: https://mirantis.github.io/ktl/
plugins:
  - search
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  logo: logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.expand
    - navigation.sections
nav:
  - index.md
  - getting-started.md
  - Examples:
    - examples/generate.md
  - Reference:
    - run spec: reference/run/spec.md

