apiVersion: batch/v1
kind: Job
metadata:
  labels:
    batch.kubernetes.io/job-name: static-task
    job-name: static-task
  name: static-task
  namespace: default
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: static-task
        job-name: static-task
    spec:
      containers:
      - image: app:v1
        imagePullPolicy: IfNotPresent
        name: app
        resources: {}
        terminationMessagePath: /dev/termination-log
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
