{{- include "merge_presets" . -}}
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myapp
  labels:
    env: {{ index .Values.global "myapp/Service/myapp-svc/metadata/labels/env" }}
    app: myapp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: myapp
