clusters:
  - names: ["dev-cluster-a"]
namespaces: ["my*app"]
clusterResources:
  ["namespaces", "customresourcedefinitions.apiextensions.k8s.io"]
labelSelectors: ["skip-me!=yes"]
skip:
  - resources:
      - kind: Namespace
        name: myapp
    fields:
      - "metadata.labels.[my.escaped/label]"
  - fields:
      - "metadata.annotations.ignored-annotation"
      - "metadata.labels.ignored-label"
