// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: run.proto

package apis

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultsFilter int32

const (
	DefaultsFilter_UNKNOWN DefaultsFilter = 0
	DefaultsFilter_NONE    DefaultsFilter = 1
)

// Enum value maps for DefaultsFilter.
var (
	DefaultsFilter_name = map[int32]string{
		0: "UNKNOWN",
		1: "NONE",
	}
	DefaultsFilter_value = map[string]int32{
		"UNKNOWN": 0,
		"NONE":    1,
	}
)

func (x DefaultsFilter) Enum() *DefaultsFilter {
	p := new(DefaultsFilter)
	*p = x
	return p
}

func (x DefaultsFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultsFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_run_proto_enumTypes[0].Descriptor()
}

func (DefaultsFilter) Type() protoreflect.EnumType {
	return &file_run_proto_enumTypes[0]
}

func (x DefaultsFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultsFilter.Descriptor instead.
func (DefaultsFilter) EnumDescriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

// Pipeline defines the combination of source, filters and output.
type Pipeline struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the pipeline
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description for the pipeline
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Source specifies the origin of the manifests
	Source *Source `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Filters transform the manifests
	Filters []*Filter `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	// Output specifies the format of the result
	Output *Output `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	// Args describe pipeline parameters
	Args          *Args `protobuf:"bytes,6,opt,name=args,proto3,oneof" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{0}
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pipeline) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pipeline) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Pipeline) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Pipeline) GetOutput() *Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Pipeline) GetArgs() *Args {
	if x != nil {
		return x.Args
	}
	return nil
}

type Args struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *structpb.Struct       `protobuf:"bytes,1,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	SchemaFile    *string                `protobuf:"bytes,2,opt,name=schema_file,json=schemaFile,proto3,oneof" json:"schema_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{1}
}

func (x *Args) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Args) GetSchemaFile() string {
	if x != nil && x.SchemaFile != nil {
		return *x.SchemaFile
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kubeconfig    *KubeConfigSource      `protobuf:"bytes,1,opt,name=kubeconfig,proto3,oneof" json:"kubeconfig,omitempty"`
	Kustomize     *KustomizeSource       `protobuf:"bytes,2,opt,name=kustomize,proto3,oneof" json:"kustomize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetKubeconfig() *KubeConfigSource {
	if x != nil {
		return x.Kubeconfig
	}
	return nil
}

func (x *Source) GetKustomize() *KustomizeSource {
	if x != nil {
		return x.Kustomize
	}
	return nil
}

type KubeConfigSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Clusters      []*ClusterSelector     `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Resources     []*ResourceMatcher     `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeConfigSource) Reset() {
	*x = KubeConfigSource{}
	mi := &file_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeConfigSource) ProtoMessage() {}

func (x *KubeConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeConfigSource.ProtoReflect.Descriptor instead.
func (*KubeConfigSource) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{3}
}

func (x *KubeConfigSource) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *KubeConfigSource) GetClusters() []*ClusterSelector {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *KubeConfigSource) GetResources() []*ResourceMatcher {
	if x != nil {
		return x.Resources
	}
	return nil
}

type KustomizeSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Clusters      []*ClusterSelector     `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KustomizeSource) Reset() {
	*x = KustomizeSource{}
	mi := &file_run_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KustomizeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KustomizeSource) ProtoMessage() {}

func (x *KustomizeSource) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KustomizeSource.ProtoReflect.Descriptor instead.
func (*KustomizeSource) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{4}
}

func (x *KustomizeSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KustomizeSource) GetClusters() []*ClusterSelector {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type ClusterSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchNames    *PatternSelector       `protobuf:"bytes,1,opt,name=match_names,json=matchNames,proto3,oneof" json:"match_names,omitempty"`
	Alias         *string                `protobuf:"bytes,2,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSelector) Reset() {
	*x = ClusterSelector{}
	mi := &file_run_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSelector) ProtoMessage() {}

func (x *ClusterSelector) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSelector.ProtoReflect.Descriptor instead.
func (*ClusterSelector) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterSelector) GetMatchNames() *PatternSelector {
	if x != nil {
		return x.MatchNames
	}
	return nil
}

func (x *ClusterSelector) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

type ResourceMatcher struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MatchNames        *PatternSelector       `protobuf:"bytes,1,opt,name=match_names,json=matchNames,proto3,oneof" json:"match_names,omitempty"`
	MatchNamespaces   *PatternSelector       `protobuf:"bytes,2,opt,name=match_namespaces,json=matchNamespaces,proto3,oneof" json:"match_namespaces,omitempty"`
	MatchApiResources *PatternSelector       `protobuf:"bytes,3,opt,name=match_api_resources,json=matchApiResources,proto3,oneof" json:"match_api_resources,omitempty"`
	LabelSelectors    []string               `protobuf:"bytes,4,rep,name=label_selectors,json=labelSelectors,proto3" json:"label_selectors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceMatcher) Reset() {
	*x = ResourceMatcher{}
	mi := &file_run_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMatcher) ProtoMessage() {}

func (x *ResourceMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMatcher.ProtoReflect.Descriptor instead.
func (*ResourceMatcher) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceMatcher) GetMatchNames() *PatternSelector {
	if x != nil {
		return x.MatchNames
	}
	return nil
}

func (x *ResourceMatcher) GetMatchNamespaces() *PatternSelector {
	if x != nil {
		return x.MatchNamespaces
	}
	return nil
}

func (x *ResourceMatcher) GetMatchApiResources() *PatternSelector {
	if x != nil {
		return x.MatchApiResources
	}
	return nil
}

func (x *ResourceMatcher) GetLabelSelectors() []string {
	if x != nil {
		return x.LabelSelectors
	}
	return nil
}

type PatternSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternSelector) Reset() {
	*x = PatternSelector{}
	mi := &file_run_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternSelector) ProtoMessage() {}

func (x *PatternSelector) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternSelector.ProtoReflect.Descriptor instead.
func (*PatternSelector) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{7}
}

func (x *PatternSelector) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *PatternSelector) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          *SkipFilter            `protobuf:"bytes,1,opt,name=skip,proto3,oneof" json:"skip,omitempty"`
	Starlark      *StarlarkFilter        `protobuf:"bytes,2,opt,name=starlark,proto3,oneof" json:"starlark,omitempty"`
	Defaults      *DefaultsFilter        `protobuf:"varint,3,opt,name=defaults,proto3,enum=apis.DefaultsFilter,oneof" json:"defaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_run_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{8}
}

func (x *Filter) GetSkip() *SkipFilter {
	if x != nil {
		return x.Skip
	}
	return nil
}

func (x *Filter) GetStarlark() *StarlarkFilter {
	if x != nil {
		return x.Starlark
	}
	return nil
}

func (x *Filter) GetDefaults() DefaultsFilter {
	if x != nil && x.Defaults != nil {
		return *x.Defaults
	}
	return DefaultsFilter_UNKNOWN
}

type StarlarkFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarlarkFilter) Reset() {
	*x = StarlarkFilter{}
	mi := &file_run_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarlarkFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarlarkFilter) ProtoMessage() {}

func (x *StarlarkFilter) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarlarkFilter.ProtoReflect.Descriptor instead.
func (*StarlarkFilter) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{9}
}

func (x *StarlarkFilter) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type SkipFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceSelector    `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	KeepResources []*ResourceSelector    `protobuf:"bytes,2,rep,name=keep_resources,json=keepResources,proto3" json:"keep_resources,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipFilter) Reset() {
	*x = SkipFilter{}
	mi := &file_run_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipFilter) ProtoMessage() {}

func (x *SkipFilter) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipFilter.ProtoReflect.Descriptor instead.
func (*SkipFilter) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{10}
}

func (x *SkipFilter) GetResources() []*ResourceSelector {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SkipFilter) GetKeepResources() []*ResourceSelector {
	if x != nil {
		return x.KeepResources
	}
	return nil
}

func (x *SkipFilter) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ResourceSelector struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Group              *string                `protobuf:"bytes,1,opt,name=group,proto3,oneof" json:"group,omitempty"`
	Version            *string                `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Kind               *string                `protobuf:"bytes,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Name               *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Namespace          *string                `protobuf:"bytes,5,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	AnnotationSelector *string                `protobuf:"bytes,6,opt,name=annotation_selector,json=annotationSelector,proto3,oneof" json:"annotation_selector,omitempty"`
	LabelSelector      *string                `protobuf:"bytes,7,opt,name=label_selector,json=labelSelector,proto3,oneof" json:"label_selector,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResourceSelector) Reset() {
	*x = ResourceSelector{}
	mi := &file_run_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSelector) ProtoMessage() {}

func (x *ResourceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSelector.ProtoReflect.Descriptor instead.
func (*ResourceSelector) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceSelector) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *ResourceSelector) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ResourceSelector) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *ResourceSelector) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ResourceSelector) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *ResourceSelector) GetAnnotationSelector() string {
	if x != nil && x.AnnotationSelector != nil {
		return *x.AnnotationSelector
	}
	return ""
}

func (x *ResourceSelector) GetLabelSelector() string {
	if x != nil && x.LabelSelector != nil {
		return *x.LabelSelector
	}
	return ""
}

type Output struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	Kustomize           *KustomizeOutput           `protobuf:"bytes,1,opt,name=kustomize,proto3,oneof" json:"kustomize,omitempty"`
	KustomizeComponents *KustomizeComponentsOutput `protobuf:"bytes,2,opt,name=kustomize_components,json=kustomizeComponents,proto3,oneof" json:"kustomize_components,omitempty"`
	HelmChart           *HelmChartOutput           `protobuf:"bytes,3,opt,name=helm_chart,json=helmChart,proto3,oneof" json:"helm_chart,omitempty"`
	Csv                 *ColumnarFileOutput        `protobuf:"bytes,4,opt,name=csv,proto3,oneof" json:"csv,omitempty"`
	Table               *ColumnarFileOutput        `protobuf:"bytes,5,opt,name=table,proto3,oneof" json:"table,omitempty"`
	CrdDescriptions     *CRDDescriptionsOutput     `protobuf:"bytes,6,opt,name=crd_descriptions,json=crdDescriptions,proto3,oneof" json:"crd_descriptions,omitempty"`
	Kubectl             *KubectlOutput             `protobuf:"bytes,7,opt,name=kubectl,proto3,oneof" json:"kubectl,omitempty"`
	Json                *JSONOutput                `protobuf:"bytes,8,opt,name=json,proto3,oneof" json:"json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_run_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{12}
}

func (x *Output) GetKustomize() *KustomizeOutput {
	if x != nil {
		return x.Kustomize
	}
	return nil
}

func (x *Output) GetKustomizeComponents() *KustomizeComponentsOutput {
	if x != nil {
		return x.KustomizeComponents
	}
	return nil
}

func (x *Output) GetHelmChart() *HelmChartOutput {
	if x != nil {
		return x.HelmChart
	}
	return nil
}

func (x *Output) GetCsv() *ColumnarFileOutput {
	if x != nil {
		return x.Csv
	}
	return nil
}

func (x *Output) GetTable() *ColumnarFileOutput {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *Output) GetCrdDescriptions() *CRDDescriptionsOutput {
	if x != nil {
		return x.CrdDescriptions
	}
	return nil
}

func (x *Output) GetKubectl() *KubectlOutput {
	if x != nil {
		return x.Kubectl
	}
	return nil
}

func (x *Output) GetJson() *JSONOutput {
	if x != nil {
		return x.Json
	}
	return nil
}

type KubectlOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kubeconfig    *string                `protobuf:"bytes,1,opt,name=kubeconfig,proto3,oneof" json:"kubeconfig,omitempty"`
	Cluster       *string                `protobuf:"bytes,2,opt,name=cluster,proto3,oneof" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubectlOutput) Reset() {
	*x = KubectlOutput{}
	mi := &file_run_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubectlOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubectlOutput) ProtoMessage() {}

func (x *KubectlOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubectlOutput.ProtoReflect.Descriptor instead.
func (*KubectlOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{13}
}

func (x *KubectlOutput) GetKubeconfig() string {
	if x != nil && x.Kubeconfig != nil {
		return *x.Kubeconfig
	}
	return ""
}

func (x *KubectlOutput) GetCluster() string {
	if x != nil && x.Cluster != nil {
		return *x.Cluster
	}
	return ""
}

type KustomizeOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KustomizeOutput) Reset() {
	*x = KustomizeOutput{}
	mi := &file_run_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KustomizeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KustomizeOutput) ProtoMessage() {}

func (x *KustomizeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KustomizeOutput.ProtoReflect.Descriptor instead.
func (*KustomizeOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{14}
}

type KustomizeComponentsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KustomizeComponentsOutput) Reset() {
	*x = KustomizeComponentsOutput{}
	mi := &file_run_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KustomizeComponentsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KustomizeComponentsOutput) ProtoMessage() {}

func (x *KustomizeComponentsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KustomizeComponentsOutput.ProtoReflect.Descriptor instead.
func (*KustomizeComponentsOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{15}
}

type HelmChartOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ValuesAliases  map[string]string      `protobuf:"bytes,3,rep,name=values_aliases,json=valuesAliases,proto3" json:"values_aliases,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NoInlineValues *bool                  `protobuf:"varint,4,opt,name=no_inline_values,json=noInlineValues,proto3,oneof" json:"no_inline_values,omitempty"`
	DefaultPresets []string               `protobuf:"bytes,5,rep,name=default_presets,json=defaultPresets,proto3" json:"default_presets,omitempty"`
	RemovePresets  []string               `protobuf:"bytes,6,rep,name=remove_presets,json=removePresets,proto3" json:"remove_presets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelmChartOutput) Reset() {
	*x = HelmChartOutput{}
	mi := &file_run_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmChartOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmChartOutput) ProtoMessage() {}

func (x *HelmChartOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmChartOutput.ProtoReflect.Descriptor instead.
func (*HelmChartOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{16}
}

func (x *HelmChartOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmChartOutput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmChartOutput) GetValuesAliases() map[string]string {
	if x != nil {
		return x.ValuesAliases
	}
	return nil
}

func (x *HelmChartOutput) GetNoInlineValues() bool {
	if x != nil && x.NoInlineValues != nil {
		return *x.NoInlineValues
	}
	return false
}

func (x *HelmChartOutput) GetDefaultPresets() []string {
	if x != nil {
		return x.DefaultPresets
	}
	return nil
}

func (x *HelmChartOutput) GetRemovePresets() []string {
	if x != nil {
		return x.RemovePresets
	}
	return nil
}

type CRDDescriptionsOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRDDescriptionsOutput) Reset() {
	*x = CRDDescriptionsOutput{}
	mi := &file_run_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRDDescriptionsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRDDescriptionsOutput) ProtoMessage() {}

func (x *CRDDescriptionsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRDDescriptionsOutput.ProtoReflect.Descriptor instead.
func (*CRDDescriptionsOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{17}
}

func (x *CRDDescriptionsOutput) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type JSONOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Schema        *structpb.Struct       `protobuf:"bytes,2,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONOutput) Reset() {
	*x = JSONOutput{}
	mi := &file_run_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONOutput) ProtoMessage() {}

func (x *JSONOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONOutput.ProtoReflect.Descriptor instead.
func (*JSONOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{18}
}

func (x *JSONOutput) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *JSONOutput) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ColumnarFileOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Columns       []*ColumnOutput        `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnarFileOutput) Reset() {
	*x = ColumnarFileOutput{}
	mi := &file_run_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnarFileOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnarFileOutput) ProtoMessage() {}

func (x *ColumnarFileOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnarFileOutput.ProtoReflect.Descriptor instead.
func (*ColumnarFileOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{19}
}

func (x *ColumnarFileOutput) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *ColumnarFileOutput) GetColumns() []*ColumnOutput {
	if x != nil {
		return x.Columns
	}
	return nil
}

type ColumnOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Field         *string                `protobuf:"bytes,3,opt,name=field,proto3,oneof" json:"field,omitempty"`
	Text          *string                `protobuf:"bytes,4,opt,name=text,proto3,oneof" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnOutput) Reset() {
	*x = ColumnOutput{}
	mi := &file_run_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnOutput) ProtoMessage() {}

func (x *ColumnOutput) ProtoReflect() protoreflect.Message {
	mi := &file_run_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnOutput.ProtoReflect.Descriptor instead.
func (*ColumnOutput) Descriptor() ([]byte, []int) {
	return file_run_proto_rawDescGZIP(), []int{20}
}

func (x *ColumnOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnOutput) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ColumnOutput) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *ColumnOutput) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

var File_run_proto protoreflect.FileDescriptor

const file_run_proto_rawDesc = "" +
	"\n" +
	"\trun.proto\x12\x04apis\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\"\xe2\x01\n" +
	"\bPipeline\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x06source\x18\x03 \x01(\v2\f.apis.SourceR\x06source\x12&\n" +
	"\afilters\x18\x04 \x03(\v2\f.apis.FilterR\afilters\x12$\n" +
	"\x06output\x18\x05 \x01(\v2\f.apis.OutputR\x06output\x12#\n" +
	"\x04args\x18\x06 \x01(\v2\n" +
	".apis.ArgsH\x00R\x04args\x88\x01\x01B\a\n" +
	"\x05_args\"}\n" +
	"\x04Args\x124\n" +
	"\x06schema\x18\x01 \x01(\v2\x17.google.protobuf.StructH\x00R\x06schema\x88\x01\x01\x12$\n" +
	"\vschema_file\x18\x02 \x01(\tH\x01R\n" +
	"schemaFile\x88\x01\x01B\t\n" +
	"\a_schemaB\x0e\n" +
	"\f_schema_file\"\x9c\x01\n" +
	"\x06Source\x12;\n" +
	"\n" +
	"kubeconfig\x18\x01 \x01(\v2\x16.apis.KubeConfigSourceH\x00R\n" +
	"kubeconfig\x88\x01\x01\x128\n" +
	"\tkustomize\x18\x02 \x01(\v2\x15.apis.KustomizeSourceH\x01R\tkustomize\x88\x01\x01B\r\n" +
	"\v_kubeconfigB\f\n" +
	"\n" +
	"_kustomize\"\x9c\x01\n" +
	"\x10KubeConfigSource\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01\x121\n" +
	"\bclusters\x18\x02 \x03(\v2\x15.apis.ClusterSelectorR\bclusters\x123\n" +
	"\tresources\x18\x03 \x03(\v2\x15.apis.ResourceMatcherR\tresourcesB\a\n" +
	"\x05_path\"X\n" +
	"\x0fKustomizeSource\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x121\n" +
	"\bclusters\x18\x02 \x03(\v2\x15.apis.ClusterSelectorR\bclusters\"\x83\x01\n" +
	"\x0fClusterSelector\x12;\n" +
	"\vmatch_names\x18\x01 \x01(\v2\x15.apis.PatternSelectorH\x00R\n" +
	"matchNames\x88\x01\x01\x12\x19\n" +
	"\x05alias\x18\x02 \x01(\tH\x01R\x05alias\x88\x01\x01B\x0e\n" +
	"\f_match_namesB\b\n" +
	"\x06_alias\"\xc7\x02\n" +
	"\x0fResourceMatcher\x12;\n" +
	"\vmatch_names\x18\x01 \x01(\v2\x15.apis.PatternSelectorH\x00R\n" +
	"matchNames\x88\x01\x01\x12E\n" +
	"\x10match_namespaces\x18\x02 \x01(\v2\x15.apis.PatternSelectorH\x01R\x0fmatchNamespaces\x88\x01\x01\x12J\n" +
	"\x13match_api_resources\x18\x03 \x01(\v2\x15.apis.PatternSelectorH\x02R\x11matchApiResources\x88\x01\x01\x12'\n" +
	"\x0flabel_selectors\x18\x04 \x03(\tR\x0elabelSelectorsB\x0e\n" +
	"\f_match_namesB\x13\n" +
	"\x11_match_namespacesB\x16\n" +
	"\x14_match_api_resources\"E\n" +
	"\x0fPatternSelector\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\"\xc4\x01\n" +
	"\x06Filter\x12)\n" +
	"\x04skip\x18\x01 \x01(\v2\x10.apis.SkipFilterH\x00R\x04skip\x88\x01\x01\x125\n" +
	"\bstarlark\x18\x02 \x01(\v2\x14.apis.StarlarkFilterH\x01R\bstarlark\x88\x01\x01\x125\n" +
	"\bdefaults\x18\x03 \x01(\x0e2\x14.apis.DefaultsFilterH\x02R\bdefaults\x88\x01\x01B\a\n" +
	"\x05_skipB\v\n" +
	"\t_starlarkB\v\n" +
	"\t_defaults\"(\n" +
	"\x0eStarlarkFilter\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"\x99\x01\n" +
	"\n" +
	"SkipFilter\x124\n" +
	"\tresources\x18\x01 \x03(\v2\x16.apis.ResourceSelectorR\tresources\x12=\n" +
	"\x0ekeep_resources\x18\x02 \x03(\v2\x16.apis.ResourceSelectorR\rkeepResources\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"\xe4\x02\n" +
	"\x10ResourceSelector\x12\x19\n" +
	"\x05group\x18\x01 \x01(\tH\x00R\x05group\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x01R\aversion\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\tH\x02R\x04kind\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x03R\x04name\x88\x01\x01\x12!\n" +
	"\tnamespace\x18\x05 \x01(\tH\x04R\tnamespace\x88\x01\x01\x124\n" +
	"\x13annotation_selector\x18\x06 \x01(\tH\x05R\x12annotationSelector\x88\x01\x01\x12*\n" +
	"\x0elabel_selector\x18\a \x01(\tH\x06R\rlabelSelector\x88\x01\x01B\b\n" +
	"\x06_groupB\n" +
	"\n" +
	"\b_versionB\a\n" +
	"\x05_kindB\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_namespaceB\x16\n" +
	"\x14_annotation_selectorB\x11\n" +
	"\x0f_label_selector\"\xda\x04\n" +
	"\x06Output\x128\n" +
	"\tkustomize\x18\x01 \x01(\v2\x15.apis.KustomizeOutputH\x00R\tkustomize\x88\x01\x01\x12W\n" +
	"\x14kustomize_components\x18\x02 \x01(\v2\x1f.apis.KustomizeComponentsOutputH\x01R\x13kustomizeComponents\x88\x01\x01\x129\n" +
	"\n" +
	"helm_chart\x18\x03 \x01(\v2\x15.apis.HelmChartOutputH\x02R\thelmChart\x88\x01\x01\x12/\n" +
	"\x03csv\x18\x04 \x01(\v2\x18.apis.ColumnarFileOutputH\x03R\x03csv\x88\x01\x01\x123\n" +
	"\x05table\x18\x05 \x01(\v2\x18.apis.ColumnarFileOutputH\x04R\x05table\x88\x01\x01\x12K\n" +
	"\x10crd_descriptions\x18\x06 \x01(\v2\x1b.apis.CRDDescriptionsOutputH\x05R\x0fcrdDescriptions\x88\x01\x01\x122\n" +
	"\akubectl\x18\a \x01(\v2\x13.apis.KubectlOutputH\x06R\akubectl\x88\x01\x01\x12)\n" +
	"\x04json\x18\b \x01(\v2\x10.apis.JSONOutputH\aR\x04json\x88\x01\x01B\f\n" +
	"\n" +
	"_kustomizeB\x17\n" +
	"\x15_kustomize_componentsB\r\n" +
	"\v_helm_chartB\x06\n" +
	"\x04_csvB\b\n" +
	"\x06_tableB\x13\n" +
	"\x11_crd_descriptionsB\n" +
	"\n" +
	"\b_kubectlB\a\n" +
	"\x05_json\"n\n" +
	"\rKubectlOutput\x12#\n" +
	"\n" +
	"kubeconfig\x18\x01 \x01(\tH\x00R\n" +
	"kubeconfig\x88\x01\x01\x12\x1d\n" +
	"\acluster\x18\x02 \x01(\tH\x01R\acluster\x88\x01\x01B\r\n" +
	"\v_kubeconfigB\n" +
	"\n" +
	"\b_cluster\"\x11\n" +
	"\x0fKustomizeOutput\"\x1b\n" +
	"\x19KustomizeComponentsOutput\"\xe6\x02\n" +
	"\x0fHelmChartOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12O\n" +
	"\x0evalues_aliases\x18\x03 \x03(\v2(.apis.HelmChartOutput.ValuesAliasesEntryR\rvaluesAliases\x12-\n" +
	"\x10no_inline_values\x18\x04 \x01(\bH\x00R\x0enoInlineValues\x88\x01\x01\x12'\n" +
	"\x0fdefault_presets\x18\x05 \x03(\tR\x0edefaultPresets\x12%\n" +
	"\x0eremove_presets\x18\x06 \x03(\tR\rremovePresets\x1a@\n" +
	"\x12ValuesAliasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_no_inline_values\"9\n" +
	"\x15CRDDescriptionsOutput\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01B\a\n" +
	"\x05_path\"o\n" +
	"\n" +
	"JSONOutput\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01\x124\n" +
	"\x06schema\x18\x02 \x01(\v2\x17.google.protobuf.StructH\x01R\x06schema\x88\x01\x01B\a\n" +
	"\x05_pathB\t\n" +
	"\a_schema\"d\n" +
	"\x12ColumnarFileOutput\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01\x12,\n" +
	"\acolumns\x18\x02 \x03(\v2\x12.apis.ColumnOutputR\acolumnsB\a\n" +
	"\x05_path\"\xa0\x01\n" +
	"\fColumnOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05field\x18\x03 \x01(\tH\x01R\x05field\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x04 \x01(\tH\x02R\x04text\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_fieldB\a\n" +
	"\x05_text*'\n" +
	"\x0eDefaultsFilter\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04NONE\x10\x012H\n" +
	"\x03KTL\x12A\n" +
	"\x06Config\x12\x16.google.protobuf.Empty\x1a\x0e.apis.Pipeline\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/configB\"Z github.com/Mirantis/ktl/pkg/apisb\x06proto3"

var (
	file_run_proto_rawDescOnce sync.Once
	file_run_proto_rawDescData []byte
)

func file_run_proto_rawDescGZIP() []byte {
	file_run_proto_rawDescOnce.Do(func() {
		file_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_run_proto_rawDesc), len(file_run_proto_rawDesc)))
	})
	return file_run_proto_rawDescData
}

var file_run_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_run_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_run_proto_goTypes = []any{
	(DefaultsFilter)(0),               // 0: apis.DefaultsFilter
	(*Pipeline)(nil),                  // 1: apis.Pipeline
	(*Args)(nil),                      // 2: apis.Args
	(*Source)(nil),                    // 3: apis.Source
	(*KubeConfigSource)(nil),          // 4: apis.KubeConfigSource
	(*KustomizeSource)(nil),           // 5: apis.KustomizeSource
	(*ClusterSelector)(nil),           // 6: apis.ClusterSelector
	(*ResourceMatcher)(nil),           // 7: apis.ResourceMatcher
	(*PatternSelector)(nil),           // 8: apis.PatternSelector
	(*Filter)(nil),                    // 9: apis.Filter
	(*StarlarkFilter)(nil),            // 10: apis.StarlarkFilter
	(*SkipFilter)(nil),                // 11: apis.SkipFilter
	(*ResourceSelector)(nil),          // 12: apis.ResourceSelector
	(*Output)(nil),                    // 13: apis.Output
	(*KubectlOutput)(nil),             // 14: apis.KubectlOutput
	(*KustomizeOutput)(nil),           // 15: apis.KustomizeOutput
	(*KustomizeComponentsOutput)(nil), // 16: apis.KustomizeComponentsOutput
	(*HelmChartOutput)(nil),           // 17: apis.HelmChartOutput
	(*CRDDescriptionsOutput)(nil),     // 18: apis.CRDDescriptionsOutput
	(*JSONOutput)(nil),                // 19: apis.JSONOutput
	(*ColumnarFileOutput)(nil),        // 20: apis.ColumnarFileOutput
	(*ColumnOutput)(nil),              // 21: apis.ColumnOutput
	nil,                               // 22: apis.HelmChartOutput.ValuesAliasesEntry
	(*structpb.Struct)(nil),           // 23: google.protobuf.Struct
	(*emptypb.Empty)(nil),             // 24: google.protobuf.Empty
}
var file_run_proto_depIdxs = []int32{
	3,  // 0: apis.Pipeline.source:type_name -> apis.Source
	9,  // 1: apis.Pipeline.filters:type_name -> apis.Filter
	13, // 2: apis.Pipeline.output:type_name -> apis.Output
	2,  // 3: apis.Pipeline.args:type_name -> apis.Args
	23, // 4: apis.Args.schema:type_name -> google.protobuf.Struct
	4,  // 5: apis.Source.kubeconfig:type_name -> apis.KubeConfigSource
	5,  // 6: apis.Source.kustomize:type_name -> apis.KustomizeSource
	6,  // 7: apis.KubeConfigSource.clusters:type_name -> apis.ClusterSelector
	7,  // 8: apis.KubeConfigSource.resources:type_name -> apis.ResourceMatcher
	6,  // 9: apis.KustomizeSource.clusters:type_name -> apis.ClusterSelector
	8,  // 10: apis.ClusterSelector.match_names:type_name -> apis.PatternSelector
	8,  // 11: apis.ResourceMatcher.match_names:type_name -> apis.PatternSelector
	8,  // 12: apis.ResourceMatcher.match_namespaces:type_name -> apis.PatternSelector
	8,  // 13: apis.ResourceMatcher.match_api_resources:type_name -> apis.PatternSelector
	11, // 14: apis.Filter.skip:type_name -> apis.SkipFilter
	10, // 15: apis.Filter.starlark:type_name -> apis.StarlarkFilter
	0,  // 16: apis.Filter.defaults:type_name -> apis.DefaultsFilter
	12, // 17: apis.SkipFilter.resources:type_name -> apis.ResourceSelector
	12, // 18: apis.SkipFilter.keep_resources:type_name -> apis.ResourceSelector
	15, // 19: apis.Output.kustomize:type_name -> apis.KustomizeOutput
	16, // 20: apis.Output.kustomize_components:type_name -> apis.KustomizeComponentsOutput
	17, // 21: apis.Output.helm_chart:type_name -> apis.HelmChartOutput
	20, // 22: apis.Output.csv:type_name -> apis.ColumnarFileOutput
	20, // 23: apis.Output.table:type_name -> apis.ColumnarFileOutput
	18, // 24: apis.Output.crd_descriptions:type_name -> apis.CRDDescriptionsOutput
	14, // 25: apis.Output.kubectl:type_name -> apis.KubectlOutput
	19, // 26: apis.Output.json:type_name -> apis.JSONOutput
	22, // 27: apis.HelmChartOutput.values_aliases:type_name -> apis.HelmChartOutput.ValuesAliasesEntry
	23, // 28: apis.JSONOutput.schema:type_name -> google.protobuf.Struct
	21, // 29: apis.ColumnarFileOutput.columns:type_name -> apis.ColumnOutput
	24, // 30: apis.KTL.Config:input_type -> google.protobuf.Empty
	1,  // 31: apis.KTL.Config:output_type -> apis.Pipeline
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_run_proto_init() }
func file_run_proto_init() {
	if File_run_proto != nil {
		return
	}
	file_run_proto_msgTypes[0].OneofWrappers = []any{}
	file_run_proto_msgTypes[1].OneofWrappers = []any{}
	file_run_proto_msgTypes[2].OneofWrappers = []any{}
	file_run_proto_msgTypes[3].OneofWrappers = []any{}
	file_run_proto_msgTypes[5].OneofWrappers = []any{}
	file_run_proto_msgTypes[6].OneofWrappers = []any{}
	file_run_proto_msgTypes[8].OneofWrappers = []any{}
	file_run_proto_msgTypes[11].OneofWrappers = []any{}
	file_run_proto_msgTypes[12].OneofWrappers = []any{}
	file_run_proto_msgTypes[13].OneofWrappers = []any{}
	file_run_proto_msgTypes[16].OneofWrappers = []any{}
	file_run_proto_msgTypes[17].OneofWrappers = []any{}
	file_run_proto_msgTypes[18].OneofWrappers = []any{}
	file_run_proto_msgTypes[19].OneofWrappers = []any{}
	file_run_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_run_proto_rawDesc), len(file_run_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_run_proto_goTypes,
		DependencyIndexes: file_run_proto_depIdxs,
		EnumInfos:         file_run_proto_enumTypes,
		MessageInfos:      file_run_proto_msgTypes,
	}.Build()
	File_run_proto = out.File
	file_run_proto_goTypes = nil
	file_run_proto_depIdxs = nil
}
