apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-svc
  namespace: myapp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: myapp
