apiVersion: batch/v1
kind: Job
metadata:
  name: ignored-task
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: app
          image: app:v1
