# This scenario generates export for multiple cluster in "component" format.
#
# Please refer to the "export-single" examples for non-component related parameters.
clusters:
  # If multiple clusters are specified, "rekustomize" will export resources
  # as "kustomize" components. See "kustomize" documentation for more details:
  # https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md
  #
  # Component names are generated as a comma-separated list of cluster or group
  # names. Cluster may be a member of multiple groups. Main purpose of the
  # groups is to improve component naming.
  #
  # If the generated component name length exceeds "kustomize" limitation, the
  # name will be replaced with its sha256sum.
  #
  # subject to change: instead of cluster-specific components, patches and
  # resources will be put directly into cluster's "overlays" (configurable
  # default).
  - group: dev
    # "names" use shell-like patterns that will match against the cluster names
    # from your KUBECONFIG.
    names: ["dev-*"]
  - group: test
    names: ["test-cluster-[ab]"]
  - group: prod
    names: ["prod-cluster-a", "prod-cluster-b"]
export:
- namespaces:
    include: ["my*app"]
  labelSelectors: ["skip-me!=yes"]
- apiResources:
    include: ["customresourcedefinitions.apiextensions.k8s.io"]
  labelSelectors: ["skip-me!=yes"]
- apiResources:
    include: ["namespaces"]
  names:
    include: ["my*app"]
skip:
  - if:
      - kind: Namespace
        name: myapp
    fields:
      - "metadata.labels.[my.escaped/label]"
  - fields:
      - "metadata.annotations.ignored-annotation"
      - "metadata.labels.ignored-label"
