apiVersion: batch/v1
kind: CronJob
metadata:
  name: infra-canary
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: healthcheck
            image: example.com/healthcheck:v1
          restartPolicy: OnFailure
