Hide
Type "ls -T ./dev"
Enter
Show
Sleep 2.5s
Hide
Type clear
Enter
Show

Hide
Type "view ./dev/myapp/myapp-deployment.yaml"
Enter
Show
Sleep 1.5s
Down 20
Sleep 2.5s
Hide
Type "q"
Type clear
Enter
Show

Hide
Type "view ./dev/myapp/myapp-svc-service.yaml"
Enter
Show
Sleep 1.5s
Hide
Type "q"
Type clear
Enter
Show

Hide
Type "view ./dev/myapp/myapp-env-configmap.yaml"
Enter
Show
Sleep 1.5s
Hide
Type "q"
Type clear
Enter
Show

Hide
Type "ls -T ./dev"
Enter
Show
Sleep 7s
Hide
Type clear
Enter
Show
