apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: myapp
          image: myapp:v1.1
          envFrom:
            - configMapRef:
                name: myapp-env
