apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: simple-app
  namespace: simple-app
  annotations:
    dev.example.com/info: flaky-tests
    example.com/generated: extra-info
spec:
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - args:
        - --debug
        envFrom:
        - configMapRef:
            name: simple-app-env
        image: example.com/simple-app:a92bbcbf624c
        name: simple-app
